### ISSUE TITLE
debug banner still on the release

### ISSUE THREAD

**Issue by subhendukundu** [lohanidamodar/flutter_firebase_starter#1]
Hey there,
Really sleek and amazing boilerplate and starter, it helped me started in no time. :)

But I am seeing a small issue. After `flutter build apk --flavor prod` building when I installed the apk on my phone it still has the debug banner on.
Any idea why? How do we fix it?

**Comment by DUKITROX** [comment]
Hi @subhendukundu, if you installed the release apk in your phone, it should not have the debug banner. But still, the reasons you may have it can be because you where using your phone as a device to run flutter apps while developing them instead of using a virtual device. If this is your case, deleting the app and reinstalling the _release apk_ should get rid of the debug banner.

But if this was not the case for you, setting the _debugShowCheckedModeBanner_ property to false of MaterialApp should get rid of it.
`class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
    );
  }
}`
Hope this resolved your issue.
Best regards Daniel from Spain

**Comment by lohanidamodar** [comment]
@subhendukundu Yes @DUKITROX  is absolutely correct. When you build APK its will not have the debug banner. But I believe you are not talking about debug banner rather `dev` banner that I have added for development build. Its because you are building it from `main.dart` file. For production, you should use `main_prod.dart` file as `flutter build apk --flavor prod -t lib/main_prod.dart`

Thank you for your support. This should resolve your issue, if not feel free to reopen the issue.
